server:
  port: 8083
spring:
  thymeleaf:
    #禁用模版缓存
    cache: false
  devtools:
#    restart:
      #热部署生效
#      enabled: true
      #设置重启目录
#      additional-paths: src/main/java
      #设置不重启目录
#      exclude: src/main/resources/**
  resources:
  #    无效，因为被拦截器覆盖了 WebMvcConfigurationSupport会让自动配置失效
    static-locations: file:C:\chemic\course\,classpath:/static/


config:
  version: 0.1

